config/routes.rb
Rails.application.routes.draw do
  # mount Rswag::Ui::Engine => '/api-docs'
  # mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end
  
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:new, :create]
    end
  end

  resources :posts do
    member do
      delete 'delete', to: 'posts#destroy', as: 'delete_post'
    end
  end

  get '/recent_posts', to: 'posts#recent', as: 'recent_posts'

  resources :comments do
    member do
      delete 'delete', to: 'comments#destroy', as: 'delete_comment'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :show, :new, :create]
        end
      end
    end
  end

  # deactive the favicon route in test environment
  get '/favicon.ico', to: proc { [204, {}, []] }

  # routes for swagger documentation
  # if Rails.env.development?
  #   mount SwaggerUiEngine::Engine, at: '/api-docs'
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # include Devise::JWT::RevocationStrategies::JTIMatcher
  devise :database_authenticatable, :registerable, :validatable,
         :recoverable, :rememberable, :confirmable
  #  :jwt_authenticatable, :recoverable, :rememberable, jwt_revocation_strategy: self

  before_create :set_default_values

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  # custom method to return the three most recent posts of this user
  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end

  # method that updates the posts counter for this user.
  def update_posts_counter
    update(posts_counter: posts.count)
  end

  # this method is called when a user is created to set default values (photo and posts_counter)
  def set_default_values
    self.photo ||= "https://randomuser.me/api/portraits/men/#{rand(1..100)}.jpg"
    self.posts_counter = 0
  end

  # define roles for users
  def admin?
    role == 'admin'
  end

  # Method to generate a JWT token for this user
  def generate_jwt
    payload = { user_id: id }
    JWT.encode(payload, Rails.application.config.jwt_secret, 'HS256')
  end
end

app/controllers/users/registrations_controller.rb
class Api::V1::Users::RegistrationsController < Devise::RegistrationsController
  respond_to :json

  def create
    user = User.new(sign_up_params)

    if user.save
      render json: { user:, message: 'sign up success', is_success: true }, status: :ok
    else
      render json: { message: 'Sign up failed', is_success: false }, status: :unprocessable_entity
    end
  end
  # end

  private

  def sign_up_params
    # params.require(:user).permit(:name, :email, :password, 			 :password_confirmation)
    params.require(:user).permit(:name, :email)
  end
end

# frozen_string_literal: true

# class Users::RegistrationsController < Devise::RegistrationsController

# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

# GET /resource/sign_up
# def new
#   super
# end

# POST /resource
# def create
#   super
# end

# GET /resource/edit
# def edit
#   super
# end

# PUT /resource
# def update
#   super
# end

# DELETE /resource
# def destroy
#   super
# end

# GET /resource/cancel
# Forces the session data which is usually expired after sign
# in to be expired now. This is useful if the user wants to
# cancel oauth signing in/up in the middle of the process,
# removing all OAuth session data.
# def cancel
#   super
# end

# protected

# If you have extra params to permit, append them to the sanitizer.
# def configure_sign_up_params
#   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
# end

# If you have extra params to permit, append them to the sanitizer.
# def configure_account_update_params
#   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
# end

# The path used after sign up.
# def after_sign_up_path_for(resource)
#   super(resource)
# end

# The path used after sign up for inactive accounts.
# def after_inactive_sign_up_path_for(resource)
#   super(resource)
# end
# end

app/controllers/users/sessions_controller.rb
class Api::V1::Users::SessionsController < Devise::SessionsController
  puts 'find me in app/controllers/api/v1/users/sessions_controller.rb'
  respond_to :json
end

# frozen_string_literal: true

# class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

# GET /resource/sign_in
# def new
#   super
# end

# POST /resource/sign_in
# def create
#   super
# end

# DELETE /resource/sign_out
# def destroy
#   super
# end

# protected

# If you have extra params to permit, append them to the sanitizer.
# def configure_sign_in_params
#   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
# end
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    # update the posts counter for each user
    @users.each(&:update_posts_counter)
  end

  def show
    @user = User.includes(posts: [{ comments: :author }, :comments]).find(params[:id])

    # update the comments counter for each post
    # update the likes counter for each post
    @user.posts.each do |post|
      post.comments.each(&:update_comments_counter)
      post.likes.each(&:update_likes_counter)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class='container d-flex flex-column pt-2'>
  <h1>Users</h1>
  <ul class="user-list d-flex justify-content-center">
    <% @users.each do |user| %>
      <li class="user-item">
        <img src="<%= user.photo %>" alt="User Photo" class="user-photo">
        <div class="user-info">
          <a class="user-name label-link" href="<%= user_path(user) %>"><%= user.name %></a>
          <p class="user-posts">Number of Posts: <%= user.posts_counter %></p>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="user-details">
    <div class="user-header">
      <img src="<%= @user.photo %>" alt="User Photo" class="user-photo">
      <div class="user-info">
        <div class="user-box">
          <h2><%= @user.name %></h2>
          <p>Number of Posts: <%= @user.posts_counter %></p>
        </div>
      </div>
    </div>
    <div class="user-bio">
      <h2>Bio</h2>
      <p><%= @user.bio %></p>
    </div>
  </div>
  <div class="user-posts">
    <div class="post-list-header">
      <h4 class='post-list-title'>Recent posts</h4>
    </div>
    <% @user.recent_posts.each do |post| %>
      <div class="post-box">
        <div class="post-header">
          <a class="post-title label-link" href="<%= user_post_path(@user, post) %> "><%= post.title %></a>
          <div class="delete-post-btn">
            <% if can? :manage, post %>
              <%= form_with(url: delete_post_post_path(post), method: :delete, remote: true) do |form| %>
                <%= form.button type: :submit, class: 'btn btn-delete', data: { confirm: 'Are you sure you want to delete this post?' } do %>
                  Delete
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>

        <p><%= post.text %></p>
        <div class='comments-likes-count'>
          <p>Comments: <%= post.comments_counter %>  |  Likes: <%= post.likes_counter %></p>
        </div>
      </div>
    <% end %>
    <a class= 'link-see-all-posts btn-primary' href="<%= user_posts_path(@user) %>">See all posts</a>
  </div>    
</div>