config/routes.rb
Rails.application.routes.draw do
  # mount Rswag::Ui::Engine => '/api-docs'
  # mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end
  
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:new, :create]
    end
  end

  resources :posts do
    member do
      delete 'delete', to: 'posts#destroy', as: 'delete_post'
    end
  end

  get '/recent_posts', to: 'posts#recent', as: 'recent_posts'

  resources :comments do
    member do
      delete 'delete', to: 'comments#destroy', as: 'delete_comment'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :show, :new, :create]
        end
      end
    end
  end

  # deactive the favicon route in test environment
  get '/favicon.ico', to: proc { [204, {}, []] }

  # routes for swagger documentation
  # if Rails.env.development?
  #   mount SwaggerUiEngine::Engine, at: '/api-docs'
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # index logic comming here
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar nav-underline navbar-expand-lg bg-body-tertiary py-2 my-0" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'Blogify', root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav gap-3">
        <button id='SidebarNavButton' class="nav-link" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling" aria-label="Toggle navigation">
          <i class="fa-solid fa-sliders"></i>
        </button>
        <li class="nav-item">
          <%= content_tag(:li, link_to('New Post', new_user_post_path(current_user), class: "nav-link")) if user_signed_in? %>
        </li>
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link", 'aria-current' => "page" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              My Account
          </a>
          <ul class="dropdown-menu">
            <% unless user_signed_in? %>
              <li>
                <%= link_to 'Sign in', new_user_session_path, method: :delete, class: "dropdown-item" %>
              </li>
            <% end %>
            <% if user_signed_in? %>
              <li>
                <%= link_to 'Sign out', custom_destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </li>
            <% end %>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
          </ul>
          <% if user_signed_in? %>
            <li>
              <img src="<%= current_user.photo %>" alt="User Photo" class="navbar-user-photo">
            </li>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/_sidebar.html.erb
<div 
  class="offcanvas offcanvas-start position-relative z-0 bg-dark-subtle vh-100"
  data-bs-scroll="true" 
  data-bs-backdrop="false"
  tabindex="-1" 
  id="offcanvasScrolling"
  aria-labelledby="offcanvasScrollingLabel"
>
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasScrollingLabel">Search options</h5>
    <button id="closeSidebarButton" type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <ul class="list-group list-group">
      <%= link_to recent_posts_path, class: "list-group-item d-flex justify-content-between align-items-start py-3" do %>
        <div class="ms-2 me-auto fw-bold">Recent posts</div>
        <span class="badge bg-primary rounded-pill">14</span>
      <% end %>

      <%= link_to root_path, class: "list-group-item d-flex justify-content-between align-items-start py-3" do %>
        <div class="ms-2 me-auto fw-bold">Recent commented posts</div>
        <span class="badge bg-primary rounded-pill">14</span>
      <% end %>

      <%= link_to root_path, class: "list-group-item d-flex justify-content-between align-items-start py-3" do %>
        <div class="ms-2 me-auto fw-bold">Most liked posts</div>
        <span class="badge bg-primary rounded-pill">14</span>
      <% end %>

    </ul>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    console.log('DOMContentLoaded event');
    initSideBar();
  });

  document.addEventListener('turbo:load', function () {
    console.log('turbo:load event');
    initSideBar();
  });

  function handleSideBarToggle() {
    let offcanvas = document.getElementById('offcanvasScrolling');
    let hasShowClass = offcanvas.classList.contains('show');
    let mainContainer = document.getElementById('main-container');


    console.log("click event - hasShowClass: ", hasShowClass);

    sidebarState = hasShowClass ? 'hide' : 'show';
    sessionStorage.setItem('sidebarState', sidebarState);

    if (sidebarState === 'hide') {
      setTimeout(() => mainContainer.classList.toggle('flex-column-reverse', true), 300);
    } else {
      mainContainer.classList.toggle('flex-column-reverse', false);
    }
  };   


  function initSideBar() {
    let toggleButton = document.getElementById('SidebarNavButton');
    let closeSidebarButton = document.getElementById('closeSidebarButton');
    let mainContainer = document.getElementById('main-container');
    let offcanvas = document.getElementById('offcanvasScrolling');
  
    let hasShowClass = offcanvas.classList.contains('show');  
    let sidebarState = sessionStorage.getItem('sidebarState') || 'show';

    console.log("inside sidebar script - sidebarState: ", sidebarState);
    mainContainer.classList.toggle('flex-column-reverse', !hasShowClass);
    
    if (sidebarState==='show' && !hasShowClass) {
      offcanvas.classList.toggle('show', true);
    } else if (sidebarState==='hide' && hasShowClass) {
      offcanvas.classList.toggle('show', false);
    }


    closeSidebarButton.addEventListener('click', handleSideBarToggle);
    toggleButton.addEventListener('click', handleSideBarToggle);
  }
</script>

app/views/home/index.html.erb
<h1>WELCOME BLOGIFY HOMEPAGE</h1>
<p>This is the index page on this website</p>