config/routes.rb
Rails.application.routes.draw do
  # mount Rswag::Ui::Engine => '/api-docs'
  # mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end
  
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:new, :create]
    end
  end

  resources :posts do
    member do
      delete 'delete', to: 'posts#destroy', as: 'delete_post'
    end
  end

  get '/recent_posts', to: 'posts#recent', as: 'recent_posts'

  resources :comments do
    member do
      delete 'delete', to: 'comments#destroy', as: 'delete_comment'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :show, :new, :create]
        end
      end
    end
  end

  # deactive the favicon route in test environment
  get '/favicon.ico', to: proc { [204, {}, []] }

  # routes for swagger documentation
  # if Rails.env.development?
  #   mount SwaggerUiEngine::Engine, at: '/api-docs'
  # end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments
  has_many :likes
  has_rich_text :text

  # custom method which returns the 5 most recent comments for a given post.
  def recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end

  def set_counters_to_zero
    self.comments_counter = 0
    self.likes_counter = 0
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  # GET /api/v1/users/:user_id/posts
  def index
    # Check if the user exists, and if not, return a 404 response
    begin
      @user = User.find(params[:user_id])
    rescue ActiveRecord::RecordNotFound
      render json: { error: 'User not found' }, status: :not_found
      return
    end

    # Retrieve the user's posts and return them in the response
    @posts = @user.posts
    render json: @posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  load_and_authorize_resource

  def index
    @user = User.includes(posts: [{ comments: :author }, :comments]).find(params[:user_id])
  end
  
  def recent
    @recent_posts = Post.order(created_at: :desc).limit(10)
    puts @recent_posts
  end

  def show
    @post = Post.includes([{ comments: :author }, :comments]).find_by(id: params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.build(post_params)
    @post.set_counters_to_zero
    if @post.save
      flash.notice = 'New post added!'
      redirect_to user_path(@user)
    else
      flash.alert = "Post was not created! #{@post.errors.full_messages.join(', ')}"
      redirect_to new_user_post_path(@user)
    end
  end

  # DELETE /users/:user_id/posts/:id
  def destroy
    @post = Post.find(params[:id])
    @user = @post.author

    # if can?(:delete, @post) # Use CanCanCan to authorize the deletion
    @post.comments.destroy_all
    @post.likes.destroy_all
    @post.destroy
    redirect_to user_posts_path(@user), notice: 'Post was successfully deleted.'
    # else
    #   redirect_to user_posts_path(@user), alert: 'You are not authorized to delete this post.'
    # end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class='container'>   
  <div class="user-details">
    <div class="user-header">
      <img src="<%= @user.photo %>" alt="User Photo" class="user-photo">
      <div class="user-info">
        <div class="user-box">
          <h2><%= @user.name %></h2>
          <p>Number of Posts: <%= @user.posts_counter %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="user-posts">
    <% @user.posts.each do |post| %>
      <div class="post-box">
        <div class="post-header">
          <a class="post-title label-link" href="<%= user_post_path(@user, post) %> "><%= post.title %></a>
          <div class="delete-post-btn">
            <% if can? :manage, post %>
              <%= form_with(url: delete_post_post_path(post), method: :delete, remote: true) do |form| %>
                <%= form.button type: :submit, class: 'btn btn-delete', data: { confirm: 'Are you sure you want to delete this post?' } do %>
                  Delete
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <p><%= post.text %></p>
        <div class='comments-likes-count'>
          <p>Comments: <%= post.comments_counter %>  |  Likes: <%= post.likes_counter %></p>
        </div>

        <div class='comments-box'>
          <div class= 'recent-comments-header'>
            <h4 class='comments-list-title'>Recent Comments</h4>
            <div class='see-all-comments-button'>
              <a class= 'btn btn-primary' href="<%= user_post_path(@user, post) %>">Details</a>
            </div>
          </div>
          <ul class="comments-list">
            <% post.recent_comments.each do |comment| %>
              <li class="comment-item">
                <div class="comment-info">
                  <p><span class='comment-author-name'><%= comment.author.name %></span>: <%= comment.text %></p>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    <div class = "pagination-button">
      <a class = "btn btn-primary"  href="<%= user_path(@user) %>">Back</a>
    </div>
  </div>    
</div>

app/views/posts/new.html.erb
<div class='container d-flex flex-column pt-2'>
  <%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :post do |form| %>
    <h1>New Post</h1>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :text %>
      <%= form.rich_text_area :text, class: "form-control" %>
    </div>

    <%= form.submit "Create Post", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/recent.html.erb
<div class='container d-flex flex-column pt-2'>
  <h1>Recent Posts</h1>

  <div class="recent-posts">
    <% @recent_posts.each do |post| %>
      <div class="container shadow post-box p-2 mb-3">
        <div class="post-header">
          <div>
            <a class="post-title label-link" href="<%= user_post_path(post.author, post) %> ">
              <h3>
                <span class='post-title'><%= post.title %></span>
                by
                <span class='post-author'><%= post.author.name %></span>
              </h3>
            </a>
            <div class="post-date fw-medium fst-italic">
              <%= time_ago_in_words(post.created_at) %> ago
            </div>
          </div>
          <div class='d-flex'>
            <div class='see-all-comments-button'>
              <a 
                class= "btn btn-primary fa-solid fa-magnifying-glass"
                aria-label="See all comments"
                href="<%= user_post_path(post.author, post) %>"
              >
              </a>
            </div>
            <div class="delete-post-btn">
              <% if can? :manage, post %>
                <%= form_with(url: delete_post_post_path(post), method: :delete, remote: true) do |form| %>
                  <%= form.button type: :submit, class: 'btn btn-delete', data: { confirm: 'Are you sure you want to delete this post?' } do %>
                    <i class="fa-solid fa-trash" aria-label="Delete"></i>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class='comments-likes-count d-flex align-items-center'>
          <div>
            <span>Comments: <%= post.comments_counter %>  |  Likes: <%= post.likes_counter %></span>
          </div>
        </div>
        <p><%= post.text %></p>
      </div>
    <% end %>
  </div>    
</div>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Post Details</title>
</head>
  <body>
    <div class="post-box">
      <h3>
        <span class='post-title'><%= @post.title %></span>
        by
        <span class='post-author'><%= @post.author.name %></span>
      </h3>
      <p><%= @post.text %></p>
      <div class='comments-likes-count'>
        <p>Comments: <%= @post.comments_counter %>  |  Likes: <%= @post.likes_counter %></p>
      </div>
      <div class="comments-list-header">
        <div class="new-comment-button">
          <%= link_to 'Comment', new_user_post_comment_path(@post.author, @post), class: 'btn btn-primary' %>
        </div>
        <div class="new-like-button">
          <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |form| %>
            <%= form.submit "Like", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
      <div class='comments-box'>
        <h4 class='comments-list-title'>Comments</h4>  

        <ul class="comments-list">
          <% @post.comments.each do |comment| %>
            <li class="comment-item">
              <div class="comment-info">
                <p><span class='comment-author-name'><%= comment.author.name %></span>: <%= comment.text %></p>
              </div>
              <div class="comment-delete-button">
                <% if can? :manage, comment %>
                  <%= form_with(url: delete_comment_comment_path(comment), method: :delete, remote: true) do |form| %>
                    <%= form.button type: :submit, class: 'btn btn-delete', data: { confirm: 'Are you sure you?' } do %>
                      Delete
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </body>
</html>